name: '[arm,ppc,ricsv] architecture builds'
on:
  workflow_dispatch:
    branches: [ master, stable* ]
  schedule:
    - cron: '30 5 * * SUN'

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: "Test on ${{ matrix.distro }}/${{ matrix.arch }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: armv6
            distro: bullseye
          - arch: armv7
            distro: bullseye
          - arch: aarch64
            distro: bullseye
          - arch: s390x
            distro: bullseye
          - arch: ppc64le
            distro: bullseye
          - arch: riscv64
            distro: ubuntu22.04
    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@master
        name: "Run tests"
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          githubToken: ${{ github.token }}
          env: |
            CTEST_OUTPUT_ON_FAILURE: 1
            WLOG_LEVEL: 'trace'
          install: |
            sed -i '/deb-src/s/^# //' /etc/apt/sources.list
            apt-get update -q -y
            apt-get install -q -y \
              devscripts \
              equivs \
              build-essential \
              git-core \
              cmake \
              ninja-build \
              pkg-config \
              ccache \
              libpam0g-dev \
              clang
            mk-build-deps --install --tool 'apt-get --yes --no-remove --no-install-recommends' packaging/deb/freerdp-nightly/control
          run: |
            cmake -GNinja \
              -C ci/cmake-preloads/config-linux-all.txt \
              -B ci-build \
              -S . \
              -DCMAKE_INSTALL_PREFIX=/tmp/ci-test \
              -DCMAKE_C_COMPILER=/usr/bin/clang \
              -DCMAKE_CXX_COMPILER=/usr/bin/clang++ \
              -DUSE_UNWIND=OFF \
              -DUSE_EXECINFO=OFF \
              -DWITH_SANITIZE_ADDRESS=OFF
            cmake --build ci-build --parallel $(nproc) --target install
            cmake --build ci-build --parallel $(nproc) --target test
