name: Close inactive issues
on:
  schedule:
    - cron: "33 3 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v5
        with:
          days-before-stale: 30
          days-before-close: 14
          exempt-issue-labels: "pinned,help-wanted,blocker,feature"
          exempt-pr-labels: "pinned,help-wanted,blocker,feature"
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale because it has been open for 30 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 14 days since being marked as stale."
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
